name: Make tag

on:
  push:
    paths:
    - "CHANGELOG.md"
    branches:
    - main
  workflow_dispatch: {}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get version from changelog
      run: sed -r -n -e '/^## [0-9.]+/ { s|^## ([0-9.]+).*|::set-output name=version::\1|p; q }' CHANGELOG.md
      id: get_version

    - name: Ensure tag exists
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get_version.outputs.version }}
        create_annotated_tag: true
        dry_run: true
